
import { Lightbulb, Info } from 'lucide-react';

interface Observation {
  observation_type: string;
  period: string;
  description: string;
}

interface InsightPanelProps {
  observations: Observation[];
  loading?: boolean;
}

export function InsightPanel({ observations, loading }: InsightPanelProps) {
  if (loading) {
    return (
      <div className="p-6 border border-slate-200 bg-white rounded-2xl shadow-sm animate-pulse w-full">
        <div className="w-48 h-5 bg-slate-100 rounded mb-2"></div>
        <div className="w-64 h-3 bg-slate-100 rounded mb-6"></div>
        <div className="space-y-4">
          {[1,2,3].map(i => (
            <div key={i} className="flex gap-4">
              <div className="w-8 h-8 rounded-xl bg-slate-100 shrink-0"></div>
              <div className="flex-1 space-y-2">
                <div className="h-4 bg-slate-100 rounded w-1/4"></div>
                <div className="h-4 bg-slate-100 rounded w-full"></div>
                <div className="h-4 bg-slate-100 rounded w-2/3"></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // Show only top 5 insights for brevity
  const displayObs = observations.slice(0, 5);

  return (
    <div className="p-6 border border-slate-200/60 bg-white rounded-2xl shadow-sm w-full relative overflow-hidden">
      <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/5 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div>
      
      <div className="mb-6 flex items-start justify-between">
        <div>
          <h3 className="text-lg font-semibold text-slate-800 tracking-tight">Automated Insights</h3>
          <p className="text-sm text-slate-500 mt-1">Generated by the VoltVision analytics engine</p>
        </div>
      </div>

      <div className="space-y-6">
        {displayObs.map((obs, idx) => (
          <div key={idx} className="flex gap-4 items-start p-4 rounded-xl bg-slate-50 border border-slate-100">
            <div className="p-2.5 bg-amber-100 rounded-xl text-amber-600 shrink-0 mt-0.5 ring-1 ring-amber-500/10">
              <Lightbulb className="w-4 h-4" strokeWidth={2.5} />
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-600">Key Observation</span>
                <span className="text-[10px] px-2 py-0.5 rounded-md bg-white border border-slate-200 text-slate-500 font-medium">
                  {obs.observation_type.replace(/_/g, ' ')} • {obs.period}
                </span>
              </div>
              <p className="text-sm text-slate-700 leading-relaxed font-medium mb-3">{obs.description}</p>
              
              <div className="pl-3 border-l-2 border-amber-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-amber-600 block mb-1">Business Context</span>
                <p className="text-xs text-slate-500 leading-relaxed">
                  These operational deviations may impact network reliability and rider retention. Association does not establish causation.
                </p>
              </div>
            </div>
          </div>
        ))}
        {displayObs.length === 0 && (
          <div className="p-8 text-center border border-dashed border-slate-200 rounded-xl">
            <Info className="w-8 h-8 text-slate-300 mx-auto mb-3" />
            <p className="text-sm text-slate-500 font-medium">No significant deviations detected during this period.</p>
          </div>
        )}
      </div>
    </div>
  );
}
